### PR TITLE
VIH-9888 display spinner during api calls

### PR DESCRIPTION
**Pull request by shaed-parkar**
### JIRA link (if applicable) ###

VIH-9888

### Change description ###

display spinner during api calls

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by will-craig — APPROVED** [review]

**Review by will-craig — APPROVED** [review]
Happy with it from the technical point of view. You'll probably want to demo this to lorenzo before it is merged in though, as the loading on every single api request effects the user experience quite dramatically and could be considered jarring; they might want it restricted to the perticularly long requests such as fetching the Judges, or only show the loader after x amount of time.

**Comment by shaed-parkar** [comment]
> Happy with it from the technical point of view. You'll probably want to demo this to lorenzo before it is merged in though, as the loading on every single api request effects the user experience quite dramatically and could be considered jarring; they might want it restricted to the perticularly long requests such as fetching the Judges, or only show the loader after x amount of time.

Already done and with the testers too.

**Review by phildebrah — APPROVED** [review]
Display spinner test and working successfully.

**Pull request merged**
