### PR TITLE
VIH-7693 refactor hearings service

### PR DESCRIPTION
**Pull request by robertbennett1998**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/VIH-7693

### Change description ###
- Moved two methods from HearingsService to a new service (ConferenceDetailsService)
- Added a method to HearingsService to get the details to join by telephone (phone number and pin for the conference)
- Updated relevant unit tests and dependants

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by robertbennett1998** [comment]
Closing until all the unit tests have been updated

**Comment by robertbennett1998** [comment]
> If you're making wholesale changes like this, could you switch to automock in the unit tests to simplify the test setup and management, please? Thanks

I have updated the unit tests to use automock for all except EditHearingTests. There are too many tests that would need refactoring as they  do not currently mock out HearingsService. This should be raised as an new ticket.

For example, this test is testing HearingsService functionality and not the controller logic.
```C#
        [Test]
        public async Task Should_send_email_with_only_matching_participant()
        {
            _addNewParticipantRequest.Participants.Add(new EditParticipantRequest
            {
                ContactEmail = "new2@hmcts.net",
                FirstName = "Test2_FirstName",
                LastName = "Test2_LastName"
            });
            var userName = "old@hmcts.net";
            var updatedHearing = _updatedExistingParticipantHearingOriginal = new HearingDetailsResponse
            {
                Participants = _updatedExistingParticipantHearingOriginal.Participants,
                Cases = _updatedExistingParticipantHearingOriginal.Cases,
                CaseTypeName = "Unit Test",
                ScheduledDateTime = _updatedExistingParticipantHearingOriginal.ScheduledDateTime
            };
            updatedHearing.Participants[0].FirstName = "New user firstname";
            updatedHearing.Participants[0].Username = "old1@hmcts.net";
            var newParticipant = new ParticipantResponse
            {
                Id = Guid.NewGuid(),
                ContactEmail = "new@hmcts.net",
                Username = "new@hmcts.net",
                TelephoneNumber = "030434545",
                UserRoleName = "Individual"
            };
            updatedHearing.Participants.Add(newParticipant);

            _bookingsApiClient.SetupSequence(x => x.GetHearingDetailsByIdAsync(It.IsAny<Guid>()))
                .ReturnsAsync(_updatedExistingParticipantHearingOriginal)
                .ReturnsAsync(updatedHearing)
                .ReturnsAsync(updatedHearing);

            _userAccountService
                .Setup(x => x.UpdateParticipantUsername(
                    It.Is<BookingsApi.Contract.Requests.ParticipantRequest>(r => r.ContactEmail == "new@hmcts.net")))
                .Callback<BookingsApi.Contract.Requests.ParticipantRequest>(p => p.Username = userName)
                .ReturnsAsync(new User { UserName = userName, Password = "test123" });

            _userAccountService
                .Setup(x => x.UpdateParticipantUsername(
                    It.Is<BookingsApi.Contract.Requests.ParticipantRequest>(r => r.ContactEmail == "new2@hmcts.net")))
                .Callback<BookingsApi.Contract.Requests.ParticipantRequest>(p => p.Username = "old1@hmcts.net")
                .ReturnsAsync(new User { UserName = "old1@hmcts.net", Password = "test123" });

            var result = await _controller.EditHearing(_validId, _addNewParticipantRequest);
            ((OkObjectResult)result.Result).StatusCode.Should().Be(200);

            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(r =>
                    r.NotificationType == NotificationType.CreateIndividual)),
                Times.Once);

            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(r =>
                    r.NotificationType == NotificationType.HearingAmendmentJoh)),
                Times.Never);
            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(r =>
                    r.NotificationType == NotificationType.HearingAmendmentJudge)),
                Times.Never);
            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(r =>
                    r.NotificationType == NotificationType.HearingAmendmentLip)),
                Times.Never);
            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(r =>
                    r.NotificationType == NotificationType.HearingAmendmentRepresentative)),
                Times.Never);
            _bookingsApiClient.Verify(x => x.UpdateHearingDetailsAsync(It.IsAny<Guid>(),
                    It.Is<UpdateHearingRequest>(u =>
                        !u.Cases.IsNullOrEmpty() && u.QuestionnaireNotRequired == false)),
                Times.Once);
            _pollyRetryServiceMock.Verify(x => x.WaitAndRetryAsync<Exception, Task>
            (
                It.IsAny<int>(), It.IsAny<Func<int, TimeSpan>>(), It.IsAny<Action<int>>(),
                It.IsAny<Func<Task, bool>>(), It.IsAny<Func<Task<Task>>>()
            ), Times.Never);
        }
```

The other tests for the hearings controller should also be reviewed as part of that ticket as some of the tests were not testing essential parts. For example, this book hearing test which was refactored in this PR.
Before:
```C#
[Test]
        public async Task Should_book_hearing()
        {
            // setup response
            var hearingDetailsResponse = HearingResponseBuilder.Build()
                .WithEndPoints(2)
                .WithParticipant("Representative", "username1@hmcts.net")
                .WithParticipant("Individual", "fname2.lname2@hmcts.net")
                .WithParticipant("Individual", "fname3.lname3@hmcts.net")
                .WithParticipant("Judicial Office Holder", "fname4.lname4@hmcts.net")
                .WithParticipant("Judge", "judge.fudge@hmcts.net");
            _bookingsApiClient.Setup(x => x.BookNewHearingAsync(_bookNewHearingRequest))
                .ReturnsAsync(hearingDetailsResponse);

            var bookingRequest = new BookHearingRequest
            {
                BookingDetails = _bookNewHearingRequest
            };
            var result = await _controller.Post(bookingRequest);

            result.Result.Should().BeOfType<CreatedResult>();
            var createdObjectResult = (CreatedResult) result.Result;
            createdObjectResult.StatusCode.Should().Be(201);

            _bookNewHearingRequest.Participants.Any(x => string.IsNullOrWhiteSpace(x.Username)).Should().BeFalse();
            _pollyRetryServiceMock.Verify(x => x.WaitAndRetryAsync<Exception, Task>
            (
                It.IsAny<int>(), It.IsAny<Func<int, TimeSpan>>(), It.IsAny<Action<int>>(),
                It.IsAny<Func<Task, bool>>(), It.IsAny<Func<Task<Task>>>()
            ), Times.Exactly(4));

            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(notification =>
                    notification.NotificationType == NotificationType.HearingConfirmationJudge)), Times.Never);

            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(notification =>
                    notification.NotificationType == NotificationType.HearingConfirmationLip)), Times.AtLeast(1));

            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(notification =>
                    notification.NotificationType == NotificationType.HearingConfirmationRepresentative)),
                Times.AtLeast(1));

            _notificationApiMock.Verify(
                x => x.CreateNewNotificationAsync(It.Is<AddNotificationRequest>(notification =>
                    notification.NotificationType == NotificationType.HearingConfirmationJoh)), Times.AtLeast(1));
        }
```

**Review by kevin-hmcts — APPROVED** [review]
Please create the ticket to track the additional refactoring to be carried out.

**Comment by FarronF** [comment]
This merge introduced 2 major code smells along with a critical one. This is preventing https://github.com/hmcts/vh-admin-web/pull/706 from being merged in. I don't know why this one passed the quality gate when the other didn't with less issues, does anyone know why?

We need to discuss how to handle this quickly. But also we should take a look at fixing these code smells in the long term and how to handle them going forward.

**Pull request merged**
