### PR TITLE
VIH-8039 Able to add PM when the case type is generic

### PR DESCRIPTION
**Pull request by PrasannaDommalapati**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/VIH-8039

### Change description ###

- Able to add PM when the case type is generic

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by khizarkhanu-hmcts — APPROVED** [review]
All looks good to me. thanks

**Review by alberto-hortiguela — COMMENTED** [review]
LGTM

**Review by alberto-hortiguela — APPROVED** [review]
LGTM

**Review by robertbennett1998 — COMMENTED** [review]
LGTM

**Review by ZJianWang — COMMENTED** [review]
LGTM

**Pull request merged**
