### PR TITLE
VIH-9773 Admin Web Upcoming unallocated hearing navigate to manage work allocation page

### PR DESCRIPTION
**Pull request by arellison**
### **JIRA link**
https://tools.hmcts.net/jira/browse/VIH-9773

### **Change description**
When the links on the dashboard's “Upcoming unallocated hearings” panel were clicked, the Allocated hearings panel on the work allocation page did not show.

To resolve this issue, I have added an 'open' attribute to the allocate hearings detail element, which will be set true or false depending on the value of the allocateHearingsDetailOpen attribute.

### CODE REVIEW

**Review by marcogagliardi — APPROVED** [review]
👌🏽

**Review by twyfordr273 — APPROVED** [review]
Approved

**Comment by komaldabhi1509** [comment]
Approved

**Review by komaldabhi1509 — APPROVED** [review]

**Pull request merged**
