### PR TITLE
VIH-9306 validate UK phone numbers for justice users

### PR DESCRIPTION
**Pull request by shaed-parkar**
### JIRA link (if applicable) ###

VIH-9306

### Change description ###

- use same regex pattern for justice form name as add participant
- use a new NewUserRequest dto in admin web since the form has fewer fields than what Bookings API needs and reduce the coupling between Bookings API and Admin Web

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by twyfordr273 — CHANGES_REQUESTED** [review]
1. The telephone field should probably be updated to "tel" type rather than the "number" type. Number type would not allow brackets '(', ')', which should be valid in a telephone number. We have the pattern included to allow the brackets, so we should probably have the field match to allow those characters.

2. For the fields that are required we should probably add a required validator. We could also add a bit of css to indicate certain fields are required (A red asterisk or something similar)

**Comment by twyfordr273** [comment]
> 2. For the fields that are required we should probably add a required validator. We could also add a bit of css to indicate certain fields are required (A red asterisk or something similar)

Based on GDS guidelines, the asterisk will not be added. So we can forget about this one.

**Review by twyfordr273 — DISMISSED** [review]

**Comment by twyfordr273** [comment]
There are two small code smells that could be gotten rid of. But everything else is good

**Review by komaldabhi1509 — APPROVED** [review]

**Review by oliver-scott — DISMISSED** [review]

**Review by marcogagliardi — DISMISSED** [review]
👌🏽

**Comment by marcogagliardi** [comment]
only 2 code smell but not a blocker. good job

**Review by komaldabhi1509 — DISMISSED** [review]

**Review by oliver-scott — APPROVED** [review]

**Review by will-craig — APPROVED** [review]

**Pull request merged**
